### ISSUE TITLE
TODO Feature

### ISSUE THREAD

**Issue by 2zH** [2zH/emiya#2]
- [ ] add typescript support.
- [ ] add component/plugin support.
- [ ] add testcase, enable trival CI, greenKeepper.
- [ ] add linter support.
